### PR TITLE
Changes to support ppc64le

### PR DESCRIPTION
**Pull request by seth-priya**
Refreshing the changes from https://github.com/ansible/ansible-runner/pull/399

Picked up the latest code
Re-built and re-validated with the updated base image (centos:8), made required changes.

Please review, thank you!

### CODE REVIEW

**Comment by seth-priya** [comment]
@matburt @wenottingham

**Comment by AlanCoding** [comment]
recheck

**Comment by seth-priya** [comment]
any review comments on this?

**Comment by AlanCoding** [comment]
Discussion in issue, closing PR

**Pull request closed without merging**
