### PR TITLE
Respect stdout callback being set

### PR DESCRIPTION
**Pull request by willthames**
If stdout callback is set, either through config or environment
variable, it should be respected, not overridden.

### CODE REVIEW

**Comment by willthames** [comment]
This seems to work if the environment variable is set (as expected) but not if `stdout_callback` is set in ansible.cfg

It's not clear to me if there's a mechanism to respect ansible.cfg for this variable, but it's an acceptable failure for me.

**Comment by matburt** [comment]
This *does* have the effect of short circuiting some of the capability of Runner for gathering this information as part of its event payloads. I wonder if we should wrap this up into a larger effort to clarify support for ansible.cfg.

**Comment by willthames** [comment]
It's not just not supporting ansible.cfg though - there *has* to be some way to override the stdout callback - you can't possibly predict that people will want only either one of the two built in stdout callbacks

**Comment by wenottingham** [comment]
see #387

**Pull request closed without merging**
