### PR TITLE
Add stable-2.13 job

### PR DESCRIPTION
**Pull request by GomathiselviS**
Signed-off-by: GomathiselviS <gomathiselvi@gmail.com>

### CODE REVIEW

**Review by goneri — APPROVED** [review]

**Comment by goneri** [comment]
Looks good, but we need to migrate the project on the new platform first.

**Review by Shrews — CHANGES_REQUESTED** [review]
This job does nothing unless you refer to it in the `project.yaml`. Because the SF zuul cannot run these jobs, we've disabled all of them in `check|gate|post`. Only the `periodic` pipeline remains as it appears to still be running on the older zuul.

**Comment by ryanmerolle** [comment]
what is still blocking this?

**Comment by Shrews** [comment]
> what is still blocking this?

This changes the Zuul jobs. Zuul is no longer used for runner CI, therefore this change is pointless.

Closing this issue.

**Comment by ryanmerolle** [comment]
@Shrews So will another PR bring a tag forward for stable-2.13 and eventually stable-2.14?

**Pull request closed without merging**
