### PR TITLE
Build ansible-runner stable-2.10 images

### PR DESCRIPTION
**Pull request by pabelanger**
Stable 2.10 ansible-runner images, to be consume by collection content
team for testing purposes.

Signed-off-by: Paul Belanger <pabelanger@redhat.com>

### CODE REVIEW

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now 1c00bf16ec3be6eae71bc941d535f3b08e91737a

**Comment by pabelanger** [comment]
@shanemcd What are your thoughts here? We have an unofficial need to produce ansible-runner 2.10 images, for testing collection content. Given we still want to support them in the community.  Given how minimal the images are, I think we could publish them but offer some sort of note they are un-supported / best effort.

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Review by shanemcd — APPROVED** [review]

**Pull request merged**
