### PR TITLE
Refactor image build jobs

### PR DESCRIPTION
**Pull request by pabelanger**
Prepare to build ubi8 images.

Depends-On: https://github.com/ansible/ansible-core-image/pull/5
Signed-off-by: Paul Belanger <pabelanger@redhat.com>

### CODE REVIEW

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now 7a86988408eb03cde4f2806cf7ba3264bfbd0f06

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now 08d4bcd1bff06b60132a32c1fdab5908e36a36e9

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now ba83ad4296211e3675dc93817dba6d285c0f4299

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now 3df747dd3a64626bd525bcaaaa92d412be976631

**Comment by shanemcd** [comment]
recheck

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now c6a6ae2a4affa73eecce5a11db4d9e97c2e67371

**Review by shanemcd — APPROVED** [review]

**Pull request merged**
