### PR TITLE
Add boto to Docker image so we can run against AWS

### PR DESCRIPTION
**Pull request by fsproru**
Hey there, submitting a PR for adding boto library to the docker image which is necessary to run against AWS. There are more details in this issue: https://github.com/ansible/ansible/issues/15019

### CODE REVIEW

**Comment by andyfeller** [comment]
How do you decide which pip modules to package with this and which end users layer on top?  Should we add whatever is needed for azure or gce?

**Comment by fsproru** [comment]
@andyfeller, good question. I tend to make Docker images that have everything required to solve a particular task. If the goal of this image is to enable the users to run Ansible against Azure and Google cloud, I would add the packages for it.

**Comment by andyfeller** [comment]
My point is this shouldn’t be done because it’s an individual use case rather than something needed unilaterally by all ansible users.  It also doesn’t get people out of repackaging this image when they need other pip module, rpm packages, and configuration need to be customized.

**Comment by fsproru** [comment]
No worries, I’ll update the form readme with the modifications added so people willing to run against AWS can use our fork. If you want to mention the url to the fork in the original readme, that’s fine too. This way people find the image they need with the right packages installed.

**Comment by shanemcd** [comment]
I share the concerns @andyfeller mentioned above. You can always inherit `FROM ansible/ansible-runner` and do whatever you need to get the job done.

**Comment by fsproru** [comment]
Yep, makes sense. Thanks guys. Closing this one.

**Pull request closed without merging**
