### PR TITLE
Keep the callback provided in the environment variable

### PR DESCRIPTION
**Pull request by pguermo**
When the environment variable `ANSIBLE_STDOUT_CALLBACK` is set, it was ignored when calling ansible as only the callback_dir was passed.

### CODE REVIEW

**Comment by matburt** [comment]
I think it's probably worth adding some tests here to specifically verify that this won't affect Runner's internal callback.

**Comment by pguermo** [comment]
I've started to investigate to add a test to ensuire there is no regression with the ansible_runner callback but I'm facing the following problem: I need to define somewere an additional callback but in the test I need to know the absolute path to the folder containing the defintion of the callback as I expected to have the callback folder next to the test script.

I were thinking to use the parametrization of the arguments of the test function. But I don't find any way to provide the absolute path to the test script. 

```
@pytest.mark.parametrize('envvars', [
     {pytest.param('ANSIBLE_CALLBACK_PLUGINS', '???/test/integration/callback')}
])
```

Any idea ?

**Comment by matburt** [comment]
You can see here that the roles kept as subdirectories of the integration test directory are respected for relative paths, will that not work for you?

https://github.com/ansible/ansible-runner/blob/ca7a1b92a47513e8ac447797c64f1c9ad7a13988/test/integration/test_main.py#L106

**Comment by pguermo** [comment]
I've added an other callback "other_callback" in test/integration/callback.
I've added the parametrized fixtures "envvars" to the test test_display_callback::test_callback_plugin_receives_events to use or not this additional callback.

**Comment by matburt** [comment]
I don't know what you've done but you've pushed a bunch of old commits into your branch... it looks like you didn't pull-rebase correctly? You should close this PR and open a new one with just your changes.

**Pull request closed without merging**
