### PR TITLE
don't count line breaks on text boundry

### PR DESCRIPTION
**Pull request by jladdjr**
c.f. https://github.com/ansible/ansible-runner/issues/566

### CODE REVIEW

**Comment by jladdjr** [comment]
cc @AlanCoding @shanemcd

**Comment by AlanCoding** [comment]
Trying to brainstorm for a test...

Is the net effect of this that when a single line is written (verbose event), start_line will be equal to end_line?

**Comment by AlanCoding** [comment]
I wanted some more background to make this actionable, so I will put it here. I started testing with the AWX `devel` branch, which uses the existing runner 1.4.6 version.

### Job event with event data

```json
        {
            "id": 2,
            "type": "job_event",
            "event": "playbook_on_play_start",
            "counter": 2,
            "event_display": "Play Started (Hello World Sample)",
            "event_data": {
                "playbook": "hello_world.yml",
                "playbook_uuid": "9fc9ada8-5836-4c5c-a2e6-caa35efe4dbf",
                "play": "Hello World Sample",
                "play_uuid": "0242ac12-0004-45fb-bb3e-000000000006",
                "play_pattern": "all",
                "name": "Hello World Sample",
                "pattern": "all",
                "uuid": "0242ac12-0004-45fb-bb3e-000000000006"
            },
            "playbook": "hello_world.yml",
            "play": "Hello World Sample",
            "stdout": "\r\nPLAY [Hello World Sample] ******************************************************",
            "start_line": 0,
            "end_line": 2,
        },
```

(I omitted some data for brevity)

### Ordinary inventory update event

```json
        {
            "type": "inventory_update_event",
            "event": "verbose",
            "counter": 63,
            "event_display": "verbose",
            "event_data": {},
            "stdout": "\u001b[32;1m2020-11-16 15:21:34,522 DEBUG    awx.main.models.inventory Finished updating inventory computed fields, pk=24, in 0.024 seconds\u001b[0m",
            "start_line": 62,
            "end_line": 63,
```

Trying to formalize this, and getting some help from @jakemcdermott, I think there are 2 test criteria I could write:

 - The number of lines of `stdout` is equal to end_line - start line
 - The end_line of one event needs to be the start_line of the next event

I have not yet confirmed that this patch fixes the behavior for certain cases, but I'm working towards that and I might get it soon.

**Comment by pabelanger** [comment]
recheck

**Comment by AlanCoding** [comment]
Right now I'm leaning against doing this, because it looks like it would change the schema of the stdout/start_line/end_line for normal events, and I would predict a lot of disruption from that.

The core issue we were facing seems like it was an implementation but in the custom event dispatcher code in https://github.com/ansible/awx/pull/8323, and I believe we can get the job done with some patches to that.

**Pull request closed without merging**
