### PR TITLE
fixes bug that overwrites the inventory file

### PR DESCRIPTION
**Pull request by privateip**
This fix addresses a bug where the inventory file will get overwritten
due to a default value for the hosts argument when running
ansible-runner from the command line.  This is due to a change that set
the default value for the hosts argument.  This fix removes the default
value and restores the operation to run as expected.

### CODE REVIEW

**Comment by matburt** [comment]
I'm also seeing this in python 3.6

```
Traceback (most recent call last):
  File "/usr/local/bin/ansible-runner", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/ansible_runner/__main__.py", line 179, in main
    run(**run_options)
  File "/usr/local/lib/python3.6/site-packages/ansible_runner/interface.py", line 93, in run
    r = init_runner(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/ansible_runner/interface.py", line 37, in init_runner
    dump_artifacts(kwargs)
  File "/usr/local/lib/python3.6/site-packages/ansible_runner/utils.py", line 164, in dump_artifacts
    kwargs['inventory'] = dump_artifact(obj, path, 'hosts')
  File "/usr/local/lib/python3.6/site-packages/ansible_runner/utils.py", line 113, in dump_artifact
    p_sha1.update(obj)
TypeError: Unicode-objects must be encoded before hashing
```

**Comment by matburt** [comment]
actually, wasn't able to hit that above error again... not sure why, I'm going to retry, I *do* see this:

```
Traceback (most recent call last):
  File "/usr/bin/ansible-runner", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/ansible_runner/__main__.py", line 179, in main
    run(**run_options)
  File "/usr/lib/python2.7/site-packages/ansible_runner/interface.py", line 93, in run
    r = init_runner(**kwargs)
  File "/usr/lib/python2.7/site-packages/ansible_runner/interface.py", line 48, in init_runner
    rc.prepare()
  File "/usr/lib/python2.7/site-packages/ansible_runner/runner_config.py", line 135, in prepare
    self.prepare_env()
  File "/usr/lib/python2.7/site-packages/ansible_runner/runner_config.py", line 69, in prepare_env
    for pattern, password in iteritems(passwords)
  File "/usr/lib/python2.7/site-packages/ansible_runner/runner_config.py", line 69, in <dictcomp>
    for pattern, password in iteritems(passwords)
AttributeError: 'module' object has no attribute 'rcompile'
```

**Comment by privateip** [comment]
Just upated the PR with unit tests for the fix.  Found and fixed the encoding error as well.  Looking at the AttributeError now

**Comment by privateip** [comment]
Ok, everything is fixed and all tests are passing

**Pull request merged**
