### PR TITLE
implement Python logging

### PR DESCRIPTION
**Pull request by privateip**
This change implements the Python logging facility for handling message
logging to both stdout and to a debug log file.  To use the logging
facility perform the following in module code:

```
import logging
log = logging.getLogger('ansible-runner')
log.info('i can now log message')
```

To send messages to stdout use the display function in `utils.py`.

### CODE REVIEW

**Comment by privateip** [comment]
This PR should  resolve #30

**Comment by matburt** [comment]
Looks like there are conflicts with `master` now :open_mouth:

**Comment by privateip** [comment]
> Should we expose more of these details through the command line interface also?

Yes, I figure I would wait until we got #35 merged before bubbling up that option.  Once #35 is agreed upon and merged, I will add that argument.  In the mean time I opened https://github.com/ansible/ansible-runner/issues/40 to track this feature

**Comment by privateip** [comment]
PR updated per review comments and all tests are passing

**Pull request merged**
