### PR TITLE
Directories that are symlinks need to be treated as if they are a sym…

### PR DESCRIPTION
**Pull request by jbradberry**
…link file

### CODE REVIEW

**Comment by AlanCoding** [comment]
This has been tested with the content from:

https://github.com/ansible/test-playbooks/pull/134/files

**Comment by jbradberry** [comment]
In order to test this, I was making use of a checkout of https://github.com/ansible/test-playbooks/pull/134

```
(ansible-runner) [jrb@fedora ~]$ ansible-runner transmit test-playbooks/ -p has_symlink/middle/back_to_top/ping.yml > /tmp/transmit
(ansible-runner) [jrb@fedora ~]$ ansible-runner worker < /tmp/transmit > /tmp/worker
```
and you can examine the `/tmp/transmit` and `/tmp/worker` files.

**Review by shanemcd — APPROVED** [review]

**Comment by AlanCoding** [comment]
I want to get coverage added to

https://github.com/ansible/ansible-runner/blob/5ea7ed67b12abf40b7665235ba33c2f909541834/test/unit/test_utils.py#L235

But I think we've got a pretty good handle on things.

**Review by AlanCoding — APPROVED** [review]

**Review by chrismeyersfsu — APPROVED** [review]

**Comment by AlanCoding** [comment]
Proposed some tests at https://github.com/jbradberry/ansible-runner/pull/2/, all passing as expected. It goes recursive once.

**Review by chrismeyersfsu — APPROVED** [review]

**Review by AlanCoding — APPROVED** [review]

**Pull request merged**
