### PR TITLE
Added missing suppress_ansible_output to RunnerConfig

### PR DESCRIPTION
**Pull request by mtucker502**

### CODE REVIEW

**Comment by matburt** [comment]
Can you rename this PR to describe what it does and link to the issue in the body of the PR.

**Comment by mtucker502** [comment]
Added missing suppress_ansible_output to RunnerConfig for issue #174

**Comment by matburt** [comment]
Can you rebase to fix the merge conflicts and then I think we can merge this in.

**Comment by mtucker502** [comment]
Issues resolved. Re-opening.

**Comment by mtucker502** [comment]
@matburt Can we get this merged now?

**Comment by matburt** [comment]
In the future, and for other PRs that you may have open I'd ask you to please follow a better format for git commit logs: https://chris.beams.io/posts/git-commit/

**Pull request merged**
