### PR TITLE
Make class __name__ match Ansible expectation

### PR DESCRIPTION
**Pull request by AlanCoding**
Connect https://github.com/ansible/ansible-runner/issues/279

### CODE REVIEW

**Comment by matburt** [comment]
Would this obviate https://github.com/ansible/ansible-runner/pull/281 ?

**Comment by AlanCoding** [comment]
yes, it would. I tested this fix before the merge point for that.

**Comment by matburt** [comment]
This PR should remove that line then.

**Comment by AlanCoding** [comment]
For the manual testing, here it is side-by-side:

```
(ansible-runner) bash-3.2$ ansible-runner run -p test_include_role.yml foo/

PLAY [localhost] ***************************************************************

TASK [include_role : test_tag_role] ********************************************

TASK [test_tag_role : debug] ***************************************************
ok: [localhost] => {
    "msg": ""
}
localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   


PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

(ansible-runner) bash-3.2$ ansible-playbook -i localhost, -c local foo/project/test_include_role.yml

PLAY [localhost] *************************************************************************************************************************************************************

TASK [include_role : test_tag_role] ******************************************************************************************************************************************

TASK [test_tag_role : debug] *************************************************************************************************************************************************
ok: [localhost] => {
    "msg": ""
}

PLAY RECAP *******************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   


```

I am aware that the stats are printed twice, and I do not know why.

I had to add an inventory file with localhost to the test directory

```
(ansible-runner) bash-3.2$ tree foo
foo
├── inventory
└── project
    ├── roles
    │   └── test_tag_role
    │       └── tasks
    │           └── main.yml
    └── test_include_role.yml

4 directories, 3 files
```

**Comment by matburt** [comment]
We've had that issue reported a few times. Can you see if it happens if you rebase with https://github.com/ansible/ansible-runner/pull/269

**Comment by AlanCoding** [comment]
Yes, confirmed that fixes it.

```
(ansible-runner) bash-3.2$ ansible-runner run -p test_include_role.yml foo/

PLAY [localhost] ***************************************************************

TASK [include_role : test_tag_role] ********************************************

TASK [test_tag_role : debug] ***************************************************
ok: [localhost] => {
    "msg": ""
}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

(ansible-runner) bash-3.2$ ansible-playbook -i localhost, -c local foo/project/test_include_role.yml

PLAY [localhost] *************************************************************************************************************************************************************

TASK [include_role : test_tag_role] ******************************************************************************************************************************************

TASK [test_tag_role : debug] *************************************************************************************************************************************************
ok: [localhost] => {
    "msg": ""
}

PLAY RECAP *******************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

```

Testing with branch

https://github.com/ansible/ansible-runner/compare/master...AlanCoding:docs_names_mergaroo?expand=1

**Comment by AlanCoding** [comment]
@bcoca I want to see if you agree that this alternative will maintain the plugin contract better.

**Comment by AlanCoding** [comment]
Added the test, if you run the test without the fix, you get:

```
(ansible-runner) bash-3.2$ py.test test/integration/test_events.py::test_include_role_events
============================================================================== test session starts ===============================================================================
platform darwin -- Python 3.6.5, pytest-4.4.1, py-1.8.0, pluggy-0.9.0
rootdir: /Users/alancoding/Documents/repos/ansible-runner
collected 1 item                                                                                                                                                                 

test/integration/test_events.py F                                                                                                                                          [100%]

==================================================================================== FAILURES ====================================================================================
____________________________________________________________________________ test_include_role_events ____________________________________________________________________________

    def test_include_role_events():
        r = run(
            private_data_dir=os.path.abspath('test/integration'),
            playbook='use_role.yml'
        )
        role_events = [event for event in r.events if event.get('event_data', {}).get('role', '') == "benthomasson.hello_role"]
        assert 'runner_on_ok' in [event['event'] for event in role_events]
        for event in role_events:
            event_data = event['event_data']
>           assert not event_data.get('warning', False)  # role use should not contain warnings
E           AssertionError: assert not True
E            +  where True = <built-in method get of dict object at 0x103689fc0>('warning', False)
E            +    where <built-in method get of dict object at 0x103689fc0> = {'pid': 47957, 'play': 'all', 'play_pattern': 'all', 'play_uuid': 'a0999b12-fe9b-7187-76b6-000000000006', ...}.get

test/integration/test_events.py:75: AssertionError
------------------------------------------------------------------------------ Captured stdout call ------------------------------------------------------------------------------

PLAY [all] *********************************************************************

TASK [benthomasson.hello_role : debug] *****************************************
 [WARNING]: Failure using method (v2_runner_on_start) in callback plugin
(<ansible.plugins.callback.awx_display.CallbackModule object at 0x10cb15eb8>):
'show_per_host_start'

ok: [localhost] => {
    "msg": "Hello world!"
}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

============================================================================ 1 failed in 1.17 seconds ============================================================================
```

**Pull request merged**
