### PR TITLE
Remove ansible-core-image support

### PR DESCRIPTION
**Pull request by pabelanger**
For downstream builds, we don't have an ansible-core image. Given we
were experimenting with ansible-core-image, we can drop this support for
now.

Signed-off-by: Paul Belanger <pabelanger@redhat.com>

### CODE REVIEW

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now ddb668af39558deb6716ad9550a7361a7406163e

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now ee49f55af9ff06dc26f9455e0b08114914c14e29

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now de740585426dc250cb6f874649ce7a191c41e0fe

**Review by shanemcd — APPROVED** [review]

**Comment by pabelanger** [comment]
recheck

**Pull request merged**
