### PR TITLE
Add debian install documentation

### PR DESCRIPTION
**Pull request by ezr-ondrej**
As we have the debian packages now, it would be nice to document it.

### CODE REVIEW

**Comment by matburt** [comment]
This PR xhou.d also add a section on building the deb. A little further down is a section on building these artifacts.

**Comment by ezr-ondrej** [comment]
@shanemcd I used your notes instead, thanks :+1: 

> This PR xhou.d also add a section on building the deb. A little further down is a section on building these artifacts.

I do not feel as it is as important for users, but if you give me the steps, I can add it as well :man_shrugging:

**Comment by matburt** [comment]
I *do* feel that it is important, and there is already a section for building the RPM:

https://github.com/ansible/ansible-runner/blob/master/docs/install.rst#building-the-rpm

**Comment by matburt** [comment]
Reopen if you get a chance to add this

**Comment by shanemcd** [comment]
@matburt I was the one that wrote the actually Debian packaging side, so it should be on me to provide that documentation. Apologies for any confusion here.. I'm going to reopen this so I can push a commit on top of @ezr-ondrej's PR when I get the time.

**Comment by ezr-ondrej** [comment]
no worries, I just can not provide more info as I do not have it :stuck_out_tongue_closed_eyes:

**Comment by AlanCoding** [comment]
⚠️  D-D-D-DANGER ZONE ⚠️

This PR is targeting the `master` branch, but the default branch was changed to `devel`. If you can change your base branch, please do that now. Otherwise you may need to close and make a new PR.

**Comment by AlanCoding** [comment]
I changed the base branch myself.

**Comment by shanemcd** [comment]
Yikes, just realized this fell through the cracks. Merging now.

**Pull request merged**
