### PR TITLE
DNM: pull FIPS related changes

### PR DESCRIPTION
**Pull request by GomathiselviS**
Signed-off-by: GomathiselviS <gomathiselvi@gmail.com>

Depends-On: https://github.com/ansible/ansible/pull/75706
Depends-On: https://github.com/ansible/ansible/pull/75707

### CODE REVIEW

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by samdoran** [comment]
What is the point of this PR?

**Comment by GomathiselviS** [comment]
This PR will pull the fixes in [75706](https://github.com/ansible/ansible/pull/75706) and [75707](https://github.com/ansible/ansible/pull/75707) until they are merged. I am using this PR as a Depends-On in [267](https://github.com/ansible-collections/arista.eos/pull/267)

**Comment by samdoran** [comment]
Closing since ansible/ansible#75706 and ansible/ansible#75707 are merged.

**Pull request closed without merging**
