### PR TITLE
Add support for parameter --ask-pass

### PR DESCRIPTION
**Pull request by pguermo**
ansible-runner --help shows that --ask-pass should be an option, but it is not supported by RunnerConfig

Fix for bug: https://github.com/ansible/ansible-runner/issues/305

### CODE REVIEW

**Comment by matburt** [comment]
Prompting at the pre-run level isn't something I think we want to support. Runner is intended to be given the password via the run(...) interface or via the private data directory.

It might be that this needs to be added if there are passwords provided via the private data dir OR with credentials on the `run(...)` interface.

**Comment by pguermo** [comment]
Indeed, I don't expect ansible-runner prompts for the passwords but ansible must prompt for the password. (When launching ansible manually, I started it with the option --ask-pass and provide the requested password.)

If ansible prompts for the passwords, ansible runner may provide them if they are defined in env/passwords. That's the purpose of the fix.

**Comment by matburt** [comment]
I think the better implementation here would be to detect whether a password prompt is needed by checking to see if `env/passwords` exists and has content. If it does then emit the `-k` and/or `-K` (sudo password prompt).

There's a whole other side to this I think that is vaulted password prompts.

**Comment by pguermo** [comment]
The fix has been reworked. The option --ask-pass is not used anymore at ansible-runner level but the option -k is passed to ansible when the file env/passwords contains passwords.

**Comment by matburt** [comment]
I think this might need to be expanded, there are two other password prompts that could be emitted as part of this chain: `-K` which is prompting for `BECOME` passwords. and `--ask-vault-pass` which is used if vault password is prompted for. The challenge here is the format of the password prompt file, see this part of the documentation:

https://ansible-runner.readthedocs.io/en/latest/intro.html#env-passwords

What I would *really* like to do (and allude to that in the comment there in the docs) is change this away from the regex matching and move towards stable matching on known ansible prompts, which I think is achievable since Ansible seems to have standardized on it.

as-is, your PR assumes (possibly incorrectly) that the password is a normal user password... but what happens if the input is only for become password (necessitating `-K` and *not* `-k`)?

**Comment by pguermo** [comment]
Indeed, the case of the -K or --ask-vault-pass was not covered by my change. Thanks to broaden my vision.

Passing --ask-pass/-k, --ask-become-pass/-K and --ask-vault-pass to ansible-runner would give you more control. Ansible-runner could then forward those parameters to ansible. 

I think the list of parameters used by ansible will be more stable than relying on the output when requesting some type of password.

**Comment by matburt** [comment]
You may need to rebase your branch with master

**Comment by pguermo** [comment]
I noticed I were implementing again the option cmdline.
The options -ask-pass/-k, --ask-become-pass/-K and --ask-vault-pass may be used to start ansible using the option --cmdline.

The pull request may be closed.

**Pull request closed without merging**
