### PR TITLE
allow ANSIBLE_HOST_KEY_CHECKING to be configured

### PR DESCRIPTION
**Pull request by ryanpetrello**

### CODE REVIEW

**Comment by wenottingham** [comment]
This still overrides the ansible.cfg config file

**Comment by ryanpetrello** [comment]
@wenottingham yep.

**Comment by wenottingham** [comment]
This still overrides the ansible.cfg config file

> @wenottingham yep.

Not really a fan of that... it then requires everything to be done outside of the project.

**Comment by ryanpetrello** [comment]
Yea, I'm not in disagreement with you, just stating that this is a how *number* of AWX-specific settings work (there's no code in runner or AWX to ascertain config values from `ansible.cfg` files - this is a long-standing issue that I'm arguing is outside the scope of _this_ PR).

**Pull request merged**
