### PR TITLE
Tag feature

### PR DESCRIPTION
**Pull request by mtucker502**
This adds support for playbook tags.

### CODE REVIEW

**Comment by matburt** [comment]
Can you rebase to fix the merge conflicts?

**Comment by mtucker502** [comment]
@matburt Can we get this merged now?

**Comment by matburt** [comment]
This looks like you based it on an old version of the process isolation branch. Re-base against `master` and we can take another look.

**Comment by mtucker502** [comment]
Hey Matt. I'm not sure what to do; I'm a bit new to some of this.

I rebased off of master and pushed my commits to my fork. I noticed the
pull request automatically grabbed the last commit. Did I do something
wrong here?

I can rebase again, but at the time I submit my updates, there are no merge
conflicts as there are now.

**Comment by matburt** [comment]
You can see here that you've picked up some changes from a branch that was rebased

image

At this point you may want to export your changes, create a new branch with just a single commit, and open a new pull request.

For authoring commit messages please see: https://chris.beams.io/posts/git-commit/

**Comment by mtucker502** [comment]
Will do @matburt. Thanks for the patience :)

**Pull request closed without merging**
