### PR TITLE
Use a file in artifacts to enumerate podman env var allow list

### PR DESCRIPTION
**Pull request by AlanCoding**

### CODE REVIEW

**Comment by AlanCoding** [comment]
See documentation for `--env-file` here:

https://docs.docker.com/engine/reference/commandline/run/

We are not putting the _values_ into the file. Because that would mean we are writing secrets to disk, and we should not do that. Only the keys are written, and these signal to podman/docker that those environment variables from the parent process should be applied to the job running inside the container.

**Comment by AlanCoding** [comment]
looks like tests are good

**Review by shanemcd — APPROVED** [review]

**Comment by AlanCoding** [comment]
I tested this along with AWX, and I'm really happy with how the results look so I'm going to go ahead with merge.

**Pull request merged**
