### PR TITLE
docs/execution_environment.rst: add a note with reference to Getting started EE guide

### PR DESCRIPTION
**Pull request by Andersson007**
This PR:
- in order to implement https://github.com/ansible-community/community-team/issues/230, adds a reference to the Get started EE guide. So unfamiliar readers, who'll get intrigued, can quickly access the info and get started.
- fixes a couple of typos found along the way

### CODE REVIEW

**Comment by Andersson007** [comment]
I don't see a relation between the red test checks and the changes, so ready for review

**Comment by Shrews** [comment]
@Andersson007 Looks fine to me. A fix for the CI failures has just merged. Please rebase this change and the tests should pass for you, then we can merge it. Thanks.

**Comment by Andersson007** [comment]
@Shrews done, thanks, PTAL

**Review by Shrews — APPROVED** [review]

**Comment by Andersson007** [comment]
@Shrews thanks for reviewing and merging!

**Pull request merged**
