### PR TITLE
Correctly define localhost in inventory

### PR DESCRIPTION
**Pull request by samdoran**
Correct explicit localhost entries to match [implicit localhost](https://docs.ansible.com/ansible/latest/inventory/implicit_localhost.html#implicit-localhost).

### CODE REVIEW

**Comment by samdoran** [comment]
recheck

**Review by shanemcd — APPROVED** [review]

**Comment by Shrews** [comment]
recheck

**Comment by samdoran** [comment]
recheck

**Comment by samdoran** [comment]
recheck

**Comment by Shrews** [comment]
recheck

**Pull request merged**
