### PR TITLE
Remove usage of psutil

### PR DESCRIPTION
**Pull request by wenottingham**
Just killpg when we're killing processes, and remove the cleanup of controlmasters in the callback.

Re: that cleanup, the cleanup code has:

```
    cp_path = os.environ.get('ANSIBLE_SSH_CONTROL_PATH', '')
    if not cp_path:
        return
```

AWX hasn't set ANSIBLE_SSH_CONTROL_PATH for playbook runs in 2+ years: https://github.com/ansible/awx/pull/1601

### CODE REVIEW

**Comment by matburt** [comment]
❤️ This fixes #466

**Review by matburt — APPROVED** [review]

**Comment by wenottingham** [comment]
regate

**Review by ryanpetrello — APPROVED** [review]
Die die die die die

**Pull request merged**
