### PR TITLE
adds new function to interface for passing playbooks directly

### PR DESCRIPTION
**Pull request by privateip**
This adds a new function to ansible_runner.interface call api().  This
function accepts the playbook as a native Python object and inventory as
a string. It will write the playbook and inventory to disk in temp and
execute the playbook.

This is the foundation for fully supporting #19

### CODE REVIEW

**Comment by privateip** [comment]
This PR addresses #18 and #19

**Comment by privateip** [comment]
@radez good catch!   kwarg description updated

**Comment by radez** [comment]
thx for the update, not sure it came in accurate though?
Shouldn't it read something like: "The inventory kwarg can be provided as either a native Python dict supporting YAML inventory structure or a string providing the path to an INI formatted hosts file."

The update feels like it indicates that you can still pass a string with INI formatted content but the code is actually looking for a file name to an INI file when you pass a string.

Thx @privateip

**Comment by privateip** [comment]
@matburt PR updated with refactoring per comments in review.

**Pull request merged**
