### PR TITLE
Enable stable-2.12 container builds.

### PR DESCRIPTION
**Pull request by GomathiselviS**
With ansible-2.12 available, stable-2.12 jobs are added to our testing.

### CODE REVIEW

**Comment by samdoran** [comment]
Is this a duplicate of #822?

**Comment by GomathiselviS** [comment]
> Is this a duplicate of #822?

@samdoran I would like to close #822 . I wasn't able to push changes to #822 because of permission issues. Hence created this PR with the required changes.

**Comment by GomathiselviS** [comment]
@samdoran Can this PR be merged?

**Review by Shrews — APPROVED** [review]

**Comment by GomathiselviS** [comment]
recheck

**Pull request merged**
