### PR TITLE
Add kerberos support for windows connection

### PR DESCRIPTION
**Pull request by pabelanger**
This adds in more support to windows connection plugin.

Depends-On: https://github.com/ansible/ansible-runner/pull/685
Signed-off-by: Paul Belanger <pabelanger@redhat.com>

### CODE REVIEW

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now b523c7bae54cb165144b5ef5ca5477692127566e

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now fda4c9ce21e96f9820206015965baf9681b9cd65

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now 40916ba1a5bc06ff102f736ddf29c4409f88dbe6

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now 9aec67ae87ae61f0a7645b1a2ef34ff60b3f0e60

**Review by shanemcd — APPROVED** [review]

**Comment by jborean93** [comment]
Considering CredSSP is also an optional component of both pywinrm and pypsrp should they also be included?

**Comment by pabelanger** [comment]
@jborean93 yes, I am going to propose that in the next PR. That way I can step through brew builds downstream

**Pull request merged**
