### PR TITLE
Cleanup test file

### PR DESCRIPTION
**Pull request by AlanCoding**

### CODE REVIEW

**Review by Shrews — CHANGES_REQUESTED** [review]
If we're going to fix such things, we should do it right and use the `tmp_path` [pytest fixture](https://docs.pytest.org/en/latest/how-to/tmp_path.html#the-tmp-path-fixture). pytest should handle the cleanup for us.

**Comment by AlanCoding** [comment]
@Shrews there is no precedent for `tmp_path` in the code base here, but there is `tmpdir.mkdir`. I'd be happy to switch to that.

https://github.com/ansible/ansible-runner/blob/cdc0961df51fa1e10b44371944aafe5ae140b98c/test/integration/test_transmit_worker_process.py#L58

**Comment by Shrews** [comment]
> @Shrews there is no precedent for `tmp_path` in the code base here, but there is `tmpdir.mkdir`. I'd be happy to switch to that.
> 
> https://github.com/ansible/ansible-runner/blob/cdc0961df51fa1e10b44371944aafe5ae140b98c/test/integration/test_transmit_worker_process.py#L58

`tmpdir` is the legacy way to do things (it's recommended to switch to `tmp_path`), but as long as we're making use of pytest facilities for this type of thing, I'm fine with that choice, if you prefer.

**Comment by samdoran** [comment]
This is something else I was cleaning up in #815, though I should have used `tmp_path` there.

**Comment by AlanCoding** [comment]
Closing in favor of that other PR

**Pull request closed without merging**
