### PR TITLE
Prepare for ansible stable-2.11 branch

### PR DESCRIPTION
**Pull request by pabelanger**
Add the missing bits needed to start officially creating 2.11 runner
iamges.

Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/860
Depends-On: https://github.com/ansible/ansible-runner/pull/662
Signed-off-by: Paul Belanger <pabelanger@redhat.com>

### CODE REVIEW

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now 916f1e0999a81f3a0db7d80df6f7b2ce1e81c7ab

**Review by shanemcd — APPROVED** [review]

**Pull request merged**
